[project]
name = "stac-asset"
version = "0.0.1"
dependencies = [
    "aiofiles>=23.1.0",
    "httpx>=0.24.1",
    "pystac>=1.7.3",
]

[project.optional-dependencies]
dev = [
    "black~=23.3",
    "mypy~=1.3",
    "pre-commit~=3.3",
    "pytest~=7.3",
    "ruff==0.0.269",
    "types-aiofiles~=23.1",
]

[tool.mypy]
strict = true
